# Generated by Copilot per user request - 2025-11-18
"""
Online simulation script for The Bag Bot.
Dry-run loop for testing ML predictions and trading decisions.
"""

import time
import json
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import logging
import argparse
from pathlib import Path
import sys
import os

# Add src to path for imports
sys.path.append(os.path.join(os.path.dirname(__file__), '..', 'src'))

from ml.feature_engineering import compute_indicators
from decision.policy import create_conservative_policy, create_aggressive_policy
import joblib

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

class OnlineSimulator:
    """Simulates live trading with ML predictions in dry-run mode."""
    
    def __init__(
        self, 
        model_path: str = "models/best_model.joblib",
        metadata_path: str = "models/metadata.json",
        policy_type: str = "conservative",
        initial_balance: float = 10000.0,
        log_file: str = "reports/executor_sim.csv"
    ):
        self.model_path = model_path
        self.metadata_path = metadata_path
        self.policy_type = policy_type
        self.initial_balance = initial_balance
        self.log_file = log_file
        
        # Initialize components
        self.model = None
        self.metadata = None
        self.feature_names = []
        self.policy = None
        
        # State tracking
        self.current_balance = initial_balance
        self.positions = []
        self.trade_history = []
        self.current_exposure = 0.0
        
        # Performance metrics
        self.total_trades = 0
        self.winning_trades = 0
        self.total_pnl = 0.0
        
        # Data storage
        self.simulation_logs = []
        
        # Setup
        self._load_model()
        self._setup_policy()
        self._setup_logging()
    
    def _load_model(self):
        """Load the trained ML model."""
        try:
            if os.path.exists(self.model_path):
                self.model = joblib.load(self.model_path)
                logger.info(f"Model loaded from {self.model_path}")
                
                if os.path.exists(self.metadata_path):
                    with open(self.metadata_path, 'r') as f:
                        self.metadata = json.load(f)
                    self.feature_names = self.metadata.get('feature_names', [])
                    logger.info(f"Loaded {len(self.feature_names)} feature names")
                else:
                    logger.warning(f"Metadata not found: {self.metadata_path}")
            else:
                logger.error(f"Model not found: {self.model_path}")
                
        except Exception as e:
            logger.error(f"Error loading model: {e}")
            self.model = None
    
    def _setup_policy(self):
        """Setup trading policy."""
        if self.policy_type.lower() == "conservative":
            self.policy = create_conservative_policy()
            logger.info("Using conservative trading policy")
        elif self.policy_type.lower() == "aggressive":
            self.policy = create_aggressive_policy()
            logger.info("Using aggressive trading policy")
        else:
            self.policy = create_conservative_policy()
            logger.warning(f"Unknown policy type {self.policy_type}, using conservative")
    
    def _setup_logging(self):
        """Setup simulation logging."""
        os.makedirs(os.path.dirname(self.log_file), exist_ok=True)
        
        # Write header if file doesn't exist
        if not os.path.exists(self.log_file):
            header = [
                'timestamp', 'price', 'prediction_label', 'prediction_prob', 
                'confidence', 'action', 'position_size', 'stop_loss', 'take_profit',
                'balance', 'exposure', 'trade_id', 'reasoning'
            ]
            
            with open(self.log_file, 'w') as f:
                f.write(','.join(header) + '\n')
    
    def generate_synthetic_market_data(self, base_price: float = 50000) -> dict:
        """Generate synthetic market data for simulation."""
        # Simulate price movement with some persistence
        change = np.random.normal(0, 0.01)  # 1% volatility
        if hasattr(self, '_last_price'):
            price = self._last_price * (1 + change)
        else:
            price = base_price * (1 + change)
        
        self._last_price = price
        
        # Generate OHLCV data
        volatility = abs(change) + np.random.uniform(0.005, 0.02)
        high = price * (1 + volatility * np.random.uniform(0.2, 1.0))
        low = price * (1 - volatility * np.random.uniform(0.2, 1.0))
        volume = np.random.exponential(1000)
        
        return {
            'timestamp': datetime.now(),
            'open': price * (1 + np.random.uniform(-0.002, 0.002)),
            'high': max(price, high),
            'low': min(price, low),
            'close': price,
            'volume': volume,
            'volatility': volatility
        }
    
    def compute_features_from_history(self, market_data: dict, history_length: int = 50) -> dict:
        """Compute features from recent market history."""
        if not hasattr(self, '_market_history'):
            self._market_history = []
        
        # Add current data to history
        self._market_history.append(market_data)
        
        # Keep only recent history
        if len(self._market_history) > history_length:
            self._market_history = self._market_history[-history_length:]
        
        # Need enough history for feature computation
        if len(self._market_history) < 30:
            return None
        
        # Convert to DataFrame and compute features
        df = pd.DataFrame(self._market_history)
        df.set_index('timestamp', inplace=True)
        
        try:
            df_features = compute_indicators(df)
            if len(df_features) > 0:
                # Return latest features as dict
                latest_features = df_features.iloc[-1].to_dict()
                return latest_features
        except Exception as e:
            logger.error(f"Error computing features: {e}")
            
        return None
    
    def make_prediction(self, features: dict) -> dict:
        """Make ML prediction from features."""
        if self.model is None or not features:
            return {
                'label': 'hold',
                'probability': 0.5,
                'confidence': 'low'
            }
        
        try:
            # Prepare feature vector
            feature_vector = []
            for feature_name in self.feature_names:
                value = features.get(feature_name, 0.0)
                feature_vector.append(value)
            
            # Make prediction
            X = np.array(feature_vector).reshape(1, -1)
            prediction = self.model.predict(X)[0]
            probabilities = self.model.predict_proba(X)[0]
            
            prob_positive = probabilities[1] if len(probabilities) > 1 else probabilities[0]
            
            # Determine confidence
            confidence = "high" if abs(prob_positive - 0.5) > 0.3 else "medium" if abs(prob_positive - 0.5) > 0.1 else "low"
            
            return {
                'label': 'buy' if prediction == 1 else 'sell',
                'probability': float(prob_positive),
                'confidence': confidence
            }
            
        except Exception as e:
            logger.error(f"Prediction error: {e}")
            return {
                'label': 'hold',
                'probability': 0.5,
                'confidence': 'low'
            }
    
    def execute_signal(self, signal, market_data: dict, trade_id: str):
        """Execute trading signal (simulated)."""
        price = market_data['close']
        
        if signal.action.value in ['buy', 'sell'] and signal.position_size > 0:
            # Calculate position value
            position_value = self.current_balance * signal.position_size
            
            # Simulate trade execution
            trade = {
                'trade_id': trade_id,
                'timestamp': market_data['timestamp'],
                'action': signal.action.value,
                'price': price,
                'size': signal.position_size,
                'value': position_value,
                'stop_loss': signal.stop_loss,
                'take_profit': signal.take_profit,
                'status': 'open'
            }
            
            self.positions.append(trade)
            self.current_exposure += signal.position_size
            self.total_trades += 1
            
            logger.info(f"TRADE EXECUTED: {signal.action.value.upper()} ${position_value:.2f} at ${price:.2f}")
            
            return trade
        
        return None
    
    def check_position_exits(self, current_price: float):
        """Check and execute position exits based on stops."""
        for position in self.positions[:]:  # Copy list to avoid modification issues
            if position['status'] != 'open':
                continue
            
            action = position['action']
            entry_price = position['price']
            stop_loss = position.get('stop_loss')
            take_profit = position.get('take_profit')
            
            exit_reason = None
            
            if action == 'buy':
                if stop_loss and current_price <= stop_loss:
                    exit_reason = 'stop_loss'
                elif take_profit and current_price >= take_profit:
                    exit_reason = 'take_profit'
            elif action == 'sell':
                if stop_loss and current_price >= stop_loss:
                    exit_reason = 'stop_loss'
                elif take_profit and current_price <= take_profit:
                    exit_reason = 'take_profit'
            
            if exit_reason:
                # Calculate P&L
                if action == 'buy':
                    pnl_pct = (current_price - entry_price) / entry_price
                else:  # sell
                    pnl_pct = (entry_price - current_price) / entry_price
                
                pnl_value = position['value'] * pnl_pct
                self.total_pnl += pnl_value
                
                if pnl_value > 0:
                    self.winning_trades += 1
                
                # Update position
                position['status'] = 'closed'
                position['exit_price'] = current_price
                position['exit_reason'] = exit_reason
                position['pnl'] = pnl_value
                position['pnl_pct'] = pnl_pct
                
                # Update exposure
                self.current_exposure -= position['size']
                self.current_exposure = max(0, self.current_exposure)  # Prevent negative
                
                # Update balance
                self.current_balance += pnl_value
                
                logger.info(f"POSITION CLOSED: {exit_reason} - P&L: ${pnl_value:.2f} ({pnl_pct:.2%})")
                
                self.trade_history.append(position)
    
    def log_simulation_step(self, market_data: dict, prediction: dict, signal, trade_id: str):
        """Log simulation step to CSV."""
        log_entry = {
            'timestamp': market_data['timestamp'].isoformat(),
            'price': market_data['close'],
            'prediction_label': prediction['label'],
            'prediction_prob': prediction['probability'],
            'confidence': prediction['confidence'],
            'action': signal.action.value,
            'position_size': signal.position_size,
            'stop_loss': signal.stop_loss or '',
            'take_profit': signal.take_profit or '',
            'balance': self.current_balance,
            'exposure': self.current_exposure,
            'trade_id': trade_id,
            'reasoning': signal.reasoning
        }
        
        self.simulation_logs.append(log_entry)
        
        # Write to CSV
        with open(self.log_file, 'a') as f:
            values = [str(log_entry[key]) for key in log_entry.keys()]
            f.write(','.join(values) + '\n')
    
    def run_simulation(self, num_cycles: int = 100, cycle_delay: float = 1.0):
        """Run the main simulation loop."""
        logger.info(f"Starting simulation for {num_cycles} cycles")
        logger.info(f"Initial balance: ${self.initial_balance:.2f}")
        logger.info(f"Policy: {self.policy_type}")
        
        try:
            for cycle in range(num_cycles):
                # Generate market data
                market_data = self.generate_synthetic_market_data()
                current_price = market_data['close']
                
                # Check for position exits
                self.check_position_exits(current_price)
                
                # Compute features
                features = self.compute_features_from_history(market_data)
                
                if features:
                    # Make prediction
                    prediction = self.make_prediction(features)
                    
                    # Get trading signal
                    portfolio_state = {
                        'balance': self.current_balance,
                        'exposure': self.current_exposure
                    }
                    
                    signal = self.policy.make_decision(
                        prediction=prediction,
                        market_data=market_data,
                        portfolio_state=portfolio_state
                    )
                    
                    # Execute signal
                    trade_id = f"sim_{cycle:04d}"
                    executed_trade = self.execute_signal(signal, market_data, trade_id)
                    
                    # Log step
                    self.log_simulation_step(market_data, prediction, signal, trade_id)
                    
                    # Progress logging
                    if cycle % 20 == 0:
                        win_rate = self.winning_trades / max(1, self.total_trades)
                        logger.info(f"Cycle {cycle}: Price=${current_price:.2f}, "
                                  f"Balance=${self.current_balance:.2f}, "
                                  f"P&L=${self.total_pnl:.2f}, "
                                  f"Trades={self.total_trades}, "
                                  f"Win Rate={win_rate:.1%}")
                
                # Wait before next cycle
                time.sleep(cycle_delay)
                
        except KeyboardInterrupt:
            logger.info("Simulation interrupted by user")
        except Exception as e:
            logger.error(f"Simulation error: {e}")
        finally:
            self._print_final_results()
    
    def _print_final_results(self):
        """Print final simulation results."""
        logger.info("=" * 50)
        logger.info("SIMULATION COMPLETE")
        logger.info("=" * 50)
        
        final_balance = self.current_balance
        total_return = ((final_balance - self.initial_balance) / self.initial_balance) * 100
        win_rate = (self.winning_trades / max(1, self.total_trades)) * 100
        
        logger.info(f"Initial Balance: ${self.initial_balance:.2f}")
        logger.info(f"Final Balance: ${final_balance:.2f}")
        logger.info(f"Total Return: {total_return:.2f}%")
        logger.info(f"Total P&L: ${self.total_pnl:.2f}")
        logger.info(f"Total Trades: {self.total_trades}")
        logger.info(f"Winning Trades: {self.winning_trades}")
        logger.info(f"Win Rate: {win_rate:.1f}%")
        logger.info(f"Open Positions: {len([p for p in self.positions if p['status'] == 'open'])}")
        logger.info(f"Current Exposure: {self.current_exposure:.2%}")
        logger.info(f"Log file: {self.log_file}")

def main():
    parser = argparse.ArgumentParser(description='Run online trading simulation')
    parser.add_argument('--model', default='models/best_model.joblib', help='Model file path')
    parser.add_argument('--metadata', default='models/metadata.json', help='Metadata file path')
    parser.add_argument('--policy', choices=['conservative', 'aggressive'], default='conservative', help='Trading policy')
    parser.add_argument('--balance', type=float, default=10000.0, help='Initial balance')
    parser.add_argument('--cycles', type=int, default=100, help='Number of simulation cycles')
    parser.add_argument('--delay', type=float, default=1.0, help='Delay between cycles (seconds)')
    parser.add_argument('--log-file', default='reports/executor_sim.csv', help='Output log file')
    
    args = parser.parse_args()
    
    simulator = OnlineSimulator(
        model_path=args.model,
        metadata_path=args.metadata,
        policy_type=args.policy,
        initial_balance=args.balance,
        log_file=args.log_file
    )
    
    simulator.run_simulation(num_cycles=args.cycles, cycle_delay=args.delay)

if __name__ == "__main__":
    main()