"""Centralized read-only invariants for test alignment (no runtime behavior change)."""

SINGLE_MARKET_DATA_SOURCE = True
LEARNING_GATE_ALWAYS_BLOCKED = True
EVAL_ONLY_HISTORICAL = True
HISTORICAL_REPLAY_DETERMINISTIC = True
PULSE_NON_TESTABLE = True

__all__ = [
    "SINGLE_MARKET_DATA_SOURCE",
    "LEARNING_GATE_ALWAYS_BLOCKED",
    "EVAL_ONLY_HISTORICAL",
    "HISTORICAL_REPLAY_DETERMINISTIC",
    "PULSE_NON_TESTABLE",
]
